### ISSUE TITLE
No firmware selection

### ISSUE THREAD

**Issue by ApophysX** [PSTools/PS4-Xplorer#2]
V.1.31 Does not work correctly under 6.72, the firmware selection screen does not appear.

**Comment by xXxTheDarkprogramerxXx** [comment]
There is no longer a firmware selection screen its automated by the unjail function.

(Auto Detect Firmware and unjail)

If you say its not working correctly.

Please run whichever hen you are using a second time and try again.

**Comment by ApophysX** [comment]
Okay i use Hen 2.1.3 and try again...

[https://i.ibb.co/Wcdm8Jn/Screenshot-2021-04-07-14-36-30.png](img)

but I don't see all the directory and the temperature is also displayed incorrectly.

**Comment by ApophysX** [comment]
Okay, after reboot the PS4 Pro and load up Hen, it works now.

**Comment by xXxTheDarkprogramerxXx** [comment]
Glad to hear its working after a hen reboot
